export const FETCH_NOTES = "FETCH_NOTES"
export const FETCH_NOTES_SUCCESS = "FETCH_NOTES_SUCCESS"
export const FETCH_NOTES_FAIL = "FETCH_NOTES_FAIL"

export const SAVE_NOTE = "SAVE_NOTE"
export const SAVE_NOTE_SUCCESS = "SAVE_NOTE_SUCCESS"
export const SAVE_NOTE_FAIL = "SAVE_NOTE_FAIL"

export const DELETE_NOTE = "DELETE_NOTE"
export const DELETE_NOTE_SUCCESS = "DELETE_NOTE_SUCCESS"
export const DELETE_NOTE_FAIL = "DELETE_NOTE_FAIL"
